services:
  rrhh_proyecto:
    container_name: rrhh_proyecto
    build: .
    ports:
      - "8082:8082"  # Ajusta el puerto si es necesario
    command: gunicorn --worker-class eventlet -w 1 -b 0.0.0.0:8082 app:app
